# Generated by Django 2.2.7 on 2020-03-03 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=70, null=True)),
                ('admin_id', models.IntegerField(null=True)),
                ('user_csv', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'BotTarghe',
                'verbose_name_plural': 'BotTarghe',
            },
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anagraphic', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Persona Citata',
                'verbose_name_plural': 'Persone Citate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefono')),
                ('chat_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('photo_link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Link alla foto')),
                ('transcription', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Trascrizione')),
                ('maps_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='Link alla posizione')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descrizione')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitudine')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitidine')),
                ('place', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Indirizzo/Riferimento')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Data di inserimento')),
                ('celebrities', models.ManyToManyField(blank=True, to='T.Celebrity', verbose_name='Persone Citate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='T.User', verbose_name='Inserito da')),
            ],
            options={
                'verbose_name': 'Targa',
                'verbose_name_plural': 'Targhe',
            },
        ),
    ]
